image:
  - Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Debug
  - Intermediate
  - Profile
  - Release

environment:
  matrix:
    - ARGS: ""
    - ARGS: "--shared"

install:
  - git submodule update --init
  - if "%PLATFORM%" equ "x86" set BITS=32
  - if "%PLATFORM%" equ "x64" set BITS=64
  - if "%PLATFORM%" equ "x86" set ARCH=x86
  - if "%PLATFORM%" equ "x64" set ARCH=x86_64
  - if "%PLATFORM%" equ "x86" set PLAT=Win32
  - if "%PLATFORM%" equ "x64" set PLAT=x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars%BITS%.bat"

build_script:
  - cmd: cd Dependencies
  - cmd: ..\premake --architecture=%ARCH% vs2017
  - cmd: msbuild Build\Dependencies.sln /p:Configuration=%CONFIGURATION% /p:Platform=%PLAT% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal
  - cmd: cd ..
  - cmd: premake --architecture=%ARCH% %ARGS% vs2017
  - cmd: msbuild Build\Core.sln /p:Configuration=%CONFIGURATION% /p:Platform=%PLAT% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal
