#pragma once

#include "Platform/System.h"

#if HELIUM_SHARED
# ifdef HELIUM_INSPECT_EXPORTS
#  define HELIUM_INSPECT_API HELIUM_API_EXPORT
# else
#  define HELIUM_INSPECT_API HELIUM_API_IMPORT
# endif
#else
# define HELIUM_INSPECT_API
#endif

#define HELIUM_INSPECT_PROFILE 0

#if HELIUM_PROFILE_INSTRUMENT_ALL || HELIUM_INSPECT_PROFILE
# define HELIUM_INSPECT_SCOPE_TIMER(__Str) HELIUM_PROFILE_SCOPE_TIMER(__Str)
#else
# define HELIUM_INSPECT_SCOPE_TIMER(__Str)
#endif
