@echo off

:: MongoDB
if exist mongodb\ echo Cleanup existing mongodb...
if exist mongodb\ rmdir /s /q mongodb
echo Download mongodb...
powershell $ProgressPreference = 'SilentlyContinue'; Invoke-WebRequest -Uri http://fastdl.mongodb.org/windows/mongodb-windows-x86_64-5.0.9.zip -OutFile mongodb-windows-x86_64-5.0.9.zip
echo Uncompress mongodb...
powershell $ProgressPreference = 'SilentlyContinue'; Expand-Archive -LiteralPath mongodb-windows-x86_64-5.0.9.zip -DestinationPath .
echo Cleanup archive file...
del mongodb-windows-x86_64-5.0.9.zip
echo Rename to mongodb\...
ren mongodb-win32-x86_64-windows-5.0.9 mongodb
echo Create data\ folder...
mkdir mongodb\data