name: Build

on:
  push:

jobs:

  build-linux:
    strategy:
      matrix:
        config: [Debug, Intermediate, Profile, Release]
        premake_arch: [""]
        premake_shared: ["", "--shared"]

    name: GNU/Linux ${{ matrix.config }} ${{ matrix.premake_arch }} ${{ matrix.premake_shared }}
    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
          submodules: recursive

    - name: Install System Packages
      run: |
        cd ${{ github.workspace }}/Dependencies
        sudo ./install-system-packages-ubuntu.sh

    - name: Install Local Packages
      run: |
        cd ${{ github.workspace }}/Dependencies
        ./install-local-packages-ubuntu.sh

    - name: Install vcpkg Packages
      run: |
        cd ${{ github.workspace }}/Dependencies
        ./vcpkg.sh

    # - name: Premake Dependencies
    #   run: |
    #     cd ${{ github.workspace }}/Dependencies
    #     ../premake.sh gmake2 ${{ matrix.premake_arch }}

    # - name: Build Dependencies ${{ matrix.config }}
    #   run: |
    #     cd ${{ github.workspace }}/Dependencies
    #     ../make.sh ${{ matrix.config }}

    - name: Premake Core
      run: |
        cd ${{ github.workspace }}
        ./premake.sh gmake2 ${{ matrix.premake_arch }} ${{ matrix.premake_shared }}

    - name: Build Core ${{ matrix.config }}
      run: |
        cd ${{ github.workspace }}
        ./make.sh ${{ matrix.config }}

  build-macos:
    strategy:
      matrix:
        config: [Debug, Intermediate, Profile, Release]
        premake_arch: [""]
        premake_shared: ["", "--shared"]

    name: macOS ${{ matrix.config }} ${{ matrix.premake_arch }} ${{ matrix.premake_shared }}
    runs-on: [macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
          submodules: recursive

    - name: Install vcpkg Packages
      run: |
        cd ${{ github.workspace }}/Dependencies
        ./vcpkg.sh

    # - name: Premake Dependencies
    #   run: |
    #     cd ${{ github.workspace }}/Dependencies
    #     ../premake.sh gmake2 ${{ matrix.premake_arch }}

    # - name: Build Dependencies ${{ matrix.config }}
    #   run: |
    #     cd ${{ github.workspace }}/Dependencies
    #     ../make.sh ${{ matrix.config }}

    - name: Premake Core
      run: |
        cd ${{ github.workspace }}
        ./premake.sh gmake2 ${{ matrix.premake_arch }} ${{ matrix.premake_shared }}

    - name: Build Core ${{ matrix.config }}
      run: |
        cd ${{ github.workspace }}
        ./make.sh ${{ matrix.config }}

  build-windows:
    strategy:
      matrix:
        config: [Debug, Intermediate, Profile, Release]
        premake_arch: ["", "--arch=x86"]
        premake_shared: ["", "--shared"]

    name: Windows ${{ matrix.config }} ${{ matrix.premake_arch }} ${{ matrix.premake_shared }}
    runs-on: [windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
          submodules: recursive

    - name: Setup vcvars
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install Local Packages
      run: |
        cd ${{ github.workspace }}\Dependencies
        cmd.exe /c call install-local-packages-windows.bat

    - name: Install vcpkg Packages
      run: |
        cd ${{ github.workspace }}\Dependencies
        cmd.exe /c call vcpkg.bat vs2022

    # - name: Premake Dependencies
    #   run: |
    #     cd ${{ github.workspace }}\Dependencies
    #     cmd.exe /c call ..\premake.bat vs2022 ${{ matrix.premake_arch }}

    # - name: Build Dependencies x64 ${{ matrix.config }}
    #   if: ${{ matrix.premake_arch == '' }}
    #   run: |
    #     MSBuild.exe Dependencies\Build\Dependencies.sln -p:Configuration=${{ matrix.config }} /p:Platform=x64

    # - name: Build Dependencies Win32 ${{ matrix.config }}
    #   if: ${{ matrix.premake_arch == '--arch=x86' }}
    #   run: |
    #     MSBuild.exe Dependencies\Build\Dependencies.sln -p:Configuration=${{ matrix.config }} /p:Platform=Win32

    - name: Premake Core
      run: |
        cd ${{ github.workspace }}
        cmd.exe /c call premake.bat vs2022 ${{ matrix.premake_arch }} ${{ matrix.premake_shared }}

    - name: Build Core x64 ${{ matrix.config }}
      if: ${{ matrix.premake_arch == '' }}
      run: |
        MSBuild.exe Build\Core.sln -p:Configuration=${{ matrix.config }} /p:Platform=x64

    - name: Build Core Win32 ${{ matrix.config }}
      if: ${{ matrix.premake_arch == '--arch=x86' }}
      run: |
        MSBuild.exe Build\Core.sln -p:Configuration=${{ matrix.config }} /p:Platform=Win32
