name: Build

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build:
    strategy:
      matrix:
        config: [Debug, Intermediate, Profile, Release]
        premake_arch: ["", "--arch=x86"]
        premake_shared: ["", "--shared"]

    name: Windows ${{ matrix.config }} ${{ matrix.shared }}
    runs-on: [windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
          submodules: recursive

    - name: Setup vcvars
      uses: ilammy/msvc-dev-cmd@v1

    - name: Premake Dependencies
      run: |
        cd ${{ github.workspace }}\Dependencies
        cmd.exe /c call ..\premake.bat vs2022 ${{ matrix.premake_arch }}

    - name: Premake Core
      run: |
        cd ${{ github.workspace }}
        cmd.exe /c call premake.bat vs2022 ${{ matrix.premake_arch }} ${{ matrix.premake_shared }}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build Dependencies ${{ matrix.config }}
      if: ${{ matrix.premake_arch == '' }}
      run: |
        MSBuild.exe Dependencies\Build\Dependencies.sln -p:Configuration=${{ matrix.config }} /p:Platform=x64

    - name: Build Core ${{ matrix.config }}
      if: ${{ matrix.premake_arch == '' }}
      run: |
        MSBuild.exe Build\Core.sln -p:Configuration=${{ matrix.config }} /p:Platform=x64

    - name: Build Dependencies ${{ matrix.config }}
      if: ${{ matrix.premake_arch == '--arch=x86' }}
      run: |
        MSBuild.exe Dependencies\Build\Dependencies.sln -p:Configuration=${{ matrix.config }} /p:Platform=Win32

    - name: Build Core ${{ matrix.config }}
      if: ${{ matrix.premake_arch == '--arch=x86' }}
      run: |
        MSBuild.exe Build\Core.sln -p:Configuration=${{ matrix.config }} /p:Platform=Win32
